# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeomelbaSpirit
                                 A QGIS plugin
 Based on GeoMelba software, meant to be used with the serious game CAUSERIE.
 This file contains the class of the dock widget dialog with all the buttons, tab widget, image and text.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-24
        git sha              : $Format:%H$
        email                : jules.grillot@inrae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
import os
import csv
from PyQt5.QtCore import Qt
from PyQt5.Qt import QMessageBox
from PyQt5.QtWidgets import QDialog, QLabel, QPushButton, QLineEdit, QButtonGroup, QFileDialog, QRadioButton, QDialogButtonBox, QVBoxLayout, QHBoxLayout

from qgis.gui import QgsProjectionSelectionWidget
from qgis.core import QgsUnitTypes
from qgis.PyQt import uic

from .dictionnaire import (
    regular_font, create_watershed_button_name, crs_selection_label_name, output_selection_label, output_button_name,
    watershed_selection_label, information_crs_text_pt1, information_crs_text_pt2, information_crs_text_pt3,
    folder_selection_text, information_folder_text_pt1, information_folder_text_pt2, serious_game_data_folder,
    watershed_prefix, studied_element_label, studied_element_button0_label, studied_element_button1_label,
    studied_element_button2_label, season_choice_label, season_choice_button0_label, season_choice_button1_label,
    season_choice_button2_label
)

# This loads your .ui file so that PyQt can populate your plugin with the elements from Qt Designer
FORM_CLASS, _ = uic.loadUiType(os.path.join(
    os.path.dirname(__file__), 'geomelba_spirit_dialog_base.ui'))


class GeomelbaSpiritDialog(QDialog, FORM_CLASS):
    def __init__(self, parent=None):
        super(GeomelbaSpiritDialog, self).__init__(parent)
        self.path = os.path.dirname(__file__) + serious_game_data_folder
        self.setupUi(self)
        self.setWindowFlags(Qt.Window |
                            Qt.WindowSystemMenuHint |
                            Qt.WindowMinMaxButtonsHint |
                            Qt.WindowCloseButtonHint)

        # Create main layout
        main_layout = QVBoxLayout()
        main_layout.setSpacing(30)  # Set spacing between elements

        self.setLayout(main_layout)
        # Initialization of the button box
        self.button_box.accepted.connect(self.accept)
        self.button_box.rejected.connect(self.reject)
        self.button_box.setEnabled(False)

        # Watershed buttons
        self.watershed_button_group = QButtonGroup()

        self.watershed_button_group.setExclusive(True)
        self.init_button_watershed(watershed_prefix)
        button_create_watershed = QPushButton(self)
        button_create_watershed.setText(create_watershed_button_name)

        button_create_watershed.setAccessibleName("create_watershed")
        button_create_watershed.setCheckable(True)
        button_create_watershed.setFont(regular_font)
        button_create_watershed.setFixedSize(300, 30)  # Width: 150px, Height: 40px

        self.watershed_button_group.addButton(button_create_watershed)
        self.watershed_button_group.buttonToggled.connect(self.valid_path)
        main_layout.addSpacing(10)
        # Add watershed buttons to layout
        watershed_layout = QVBoxLayout()
        main_layout.addSpacing(50)
        main_layout.addLayout(watershed_layout)
        for button in self.watershed_button_group.buttons():
            watershed_layout.addWidget(button)
        
        watershed_layout.addWidget(button_create_watershed)
        watershed_layout.setSpacing(20)
        # Add spacing between watershed buttons and season buttons
        main_layout.addSpacing(150)
        # Season choice buttons
        label_season = QLabel(self)
        label_season.setFont(regular_font)
        label_season.setText(season_choice_label)

        self.RadioButton_season_choice0 = QRadioButton(self)
        self.RadioButton_season_choice0.setText(season_choice_button0_label)

        self.RadioButton_season_choice1 = QRadioButton(self)
        self.RadioButton_season_choice1.setText(season_choice_button1_label)

        self.RadioButton_season_choice2 = QRadioButton(self)
        self.RadioButton_season_choice2.setText(season_choice_button2_label)

        self.season_choice_button_group = QButtonGroup()
        self.season_choice_button_group.addButton(self.RadioButton_season_choice0)
        self.season_choice_button_group.addButton(self.RadioButton_season_choice1)
        self.season_choice_button_group.addButton(self.RadioButton_season_choice2)
        self.season_choice_button_group.setExclusive(True)

        # Add season buttons to layout
        season_layout = QVBoxLayout()
        season_layout.setSpacing(0)
        season_layout.addWidget(label_season)
        season_layout.setSpacing(0)

        season_layout.addWidget(self.RadioButton_season_choice0)
        season_layout.setSpacing(0)

        season_layout.addWidget(self.RadioButton_season_choice1)
        season_layout.setSpacing(0)

        season_layout.addWidget(self.RadioButton_season_choice2)
        season_layout.setSpacing(5)


        main_layout.addLayout(season_layout)

        label_crs = QLabel(self)
        label_crs.setFont(regular_font)
        label_crs.setText(crs_selection_label_name)

        self.crs_selector = QgsProjectionSelectionWidget(self)
        self.crs_selector.setFont(regular_font)
        self.crs_selector.crsChanged.connect(self.crs_manager)

        # Add CRS selector to layout
        crs_layout = QHBoxLayout()
        crs_layout.addWidget(label_crs)
        crs_layout.addWidget(self.crs_selector)
        self.crs_selector.setFixedSize(200, 40)
        main_layout.addLayout(crs_layout)

        label_output = QLabel(self)
        label_output.setFont(regular_font)
        label_output.setText(output_selection_label)


        self.output_text = QLineEdit(self)
        self.output_text.setFont(regular_font)
        self.output_text.setEnabled(False)
        self.output_text.textChanged.connect(self.valid_path)

        self.output_button = QPushButton(self)
        self.output_button.setFont(regular_font)
        self.output_button.setText(output_button_name)
        self.output_button.setEnabled(False)
        self.output_button.clicked.connect(self.select_output_folder)

        # Add output selection to layout
        output_layout = QHBoxLayout()
        output_layout.addWidget(label_output)
        output_layout.addWidget(self.output_text)
        output_layout.addWidget(self.output_button)
        main_layout.addLayout(output_layout)

        # Add button box to layout
        main_layout.addWidget(self.button_box)

    def init_button_watershed(self, value_to_test):
        label_top = QLabel(self)
        label_top.setFont(regular_font)
        label_top.setText(watershed_selection_label)



        x_place = 500
        y_place = 500
        i = 0
        for name in os.listdir(self.path):
            if os.path.isdir(os.path.join(self.path, name)):
                if len(name.split(value_to_test, 1)) > 1:
                    button = QPushButton(self)
                    button_name = name.split(value_to_test, 1)[1]
                    if len(button_name) > 15:
                        res = [i for i in range(len(button_name)) if button_name.startswith('_', i)]
                        for i in range(len(res)):
                            if res[i] > 17:
                                button_name = button_name[0:res[i]] + '\n' + button_name[res[i] + 1:]
                                while res[i] < 30 and res[i] < len(res):
                                    i += 1
                                    if res[i] > 30:
                                        button_name = button_name[0:res[i]] + '\n' + button_name[res[i] + 1:]
                                        break
                                break
                    button_name = str(button_name.replace('_', ' ').capitalize())
                    button.setText(button_name)
                    button.setAccessibleName(str(button_name))
                    button.setCheckable(True)
                    button.setFixedSize(300, 30) 
                    self.watershed_button_group.addButton(button)
                    i = i + 1

    def crs_manager(self):
        crs = self.crs_selector.crs()
        if crs.mapUnits() != 0:
            unit = QgsUnitTypes.encodeUnit(crs.mapUnits())
            QMessageBox.information(None, information_crs_text_pt1, information_crs_text_pt2 + str(crs.authid()) +
                                    information_crs_text_pt3 + str(unit) + ".")

    def select_output_folder(self):
        folder = QFileDialog.getExistingDirectory(self, folder_selection_text, "", QFileDialog.ShowDirsOnly)
        self.output_text.setText(folder)

    def valid_path(self):
        if self.watershed_button_group.checkedButton() is not None:
            self.output_button.setEnabled(True)
            self.output_text.setEnabled(True)
            if os.path.exists(self.output_text.text()):
                self.button_box.setEnabled(True)
                if os.path.exists(self.output_text.text() + "/" + self.watershed_button_group.button(
                        self.watershed_button_group.checkedId()).accessibleName().lower()):
                    QMessageBox.information(None, information_folder_text_pt1, information_folder_text_pt2)
            else:
                self.button_box.setEnabled(False)
    def get_selected_season(self):
        """Function to get the selected season from the radio buttons and store it in a variable."""
        if self.RadioButton_season_choice1.isChecked():
            selected_season = 'Été'
        elif self.RadioButton_season_choice0.isChecked():
            selected_season = 'Hiver'
        elif self.RadioButton_season_choice2.isChecked():
            selected_season = 'Hiver et Été'
        else:
            raise ValueError("No season selected")
        print(f"The selected season is {selected_season}")
        with open("season.csv", 'w', newline='') as csvfile:
            csvfile.write(selected_season)
        return selected_season

    def accept(self):
        try:
            selected_season = self.get_selected_season()
            summary_message = f"La saison sélectionnée c'est {selected_season}."
            QMessageBox.information(self, "Selection Summary", summary_message)
            super(GeomelbaSpiritDialog, self).accept()
        except ValueError as e:
            QMessageBox.warning(self, "Selection Error", str(e))

