# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeomelbaSpirit
                                 A QGIS plugin
 Based on GeoMelba software, meant to be used with the serious game CAUSERIE.
 This file contains the functions to use when the user configure the dock widget.
 Buttons and widget of the dock widget are controlled with functions from this file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-24
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Jules Grillot / INRAE
        email                : jules.grillot@inrae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import json
import copy
import os
# Import personnal modules
from ..dictionnaire import data_folder, watershed_prefix, config_practices_file_json, config_slope_file_json, \
    config_land_cover_file_json, config_line_type_file_json, config_ztha_file_json, \
    config_land_cover_file_winter_json, config_line_type_file_winter_json, config_ztha_file_winter_json, \
    config_land_cover_file_summer_json, config_line_type_file_summer_json, config_ztha_file_summer_json, \
    information_jsonfile_error, config_agricultural_practices_var_json, config_slope_var_json, \
    config_slope_min_var_json, config_slope_max_var_json, config_ztha_var_json, config_UH_var_json, \
    config_UH_abatement_var_json, config_UH_production_var_json, selected_season_button1_label, \
    selected_season_button0_label, config_UH_value_var_json, config_UH_low_slope_var_json, \
    config_UH_medium_slope_var_json, config_UH_high_slope_var_json, studied_element_button0_label, \
    studied_element_button1_label, studied_element_button2_label, \
    config_UH_drain_0_var_json, config_UH_drain_1_var_json, config_UH_drain_2_var_json, config_UH_drain_3_var_json


class ConfigFilesImportJS:

    def __init__(self, path=None, watershed_name=None, season=None):
        # Get multiple parameters from the CSV in the watershed directory.
        self.practices = {}
        self.slope = {}
        self.land_cover = {}
        self.abatement_type = []
        self.abatement = {}
        self.abatement_water = {}
        self.abatement_mes = {}
        self.abatement_phyto = {}
        self.production_type = []
        self.production = {}
        self.production_water = {}
        self.production_mes = {}
        self.production_phyto = {}
        self.line_type = {}
        self.abatement_type_long = []
        self.abatement_type_lat = []
        self.abatement_long = {}
        self.abatement_long_water = {}
        self.abatement_long_mes = {}
        self.abatement_long_phyto = {}
        self.abatement_lat = {}
        self.abatement_lat_water = {}
        self.abatement_lat_mes = {}
        self.abatement_lat_phyto = {}
        self.ztha_type = {}
        self.path = path + data_folder + watershed_prefix + watershed_name + "/"
        self.season = season

        self.import_config_files()

    def import_config_files(self):
        table_name = config_practices_file_json

        with open(self.path + table_name) as jsfile:
            data_agricultural_practices = json.load(jsfile)
            if config_agricultural_practices_var_json in data_agricultural_practices:
                for key in data_agricultural_practices[config_agricultural_practices_var_json]:
                    self.practices[key] = int(data_agricultural_practices[config_agricultural_practices_var_json][key])
            else:
                QMessageBox.information(None, information_jsonfile_error, table_name)

        table_name = config_slope_file_json
        with open(self.path + table_name) as jsfile:
            data_slope = json.load(jsfile)
            if config_slope_var_json in data_slope:
                for key in data_slope[config_slope_var_json]:
                    self.slope[key] = int(data_slope[config_slope_var_json][key][config_slope_min_var_json]), \
                        int(data_slope[config_slope_var_json][key][config_slope_max_var_json])
            else:
                QMessageBox.information(None, information_jsonfile_error, table_name)

        if self.season[0] == selected_season_button0_label:
            table_name = config_ztha_file_summer_json
        elif self.season[0] == selected_season_button1_label:
            table_name = config_ztha_file_winter_json

        if os.path.exists(self.path + table_name):
            with open(self.path + table_name) as jsfile:
                data_ztha = json.load(jsfile)
                if config_ztha_var_json in data_ztha:
                    for ident in data_ztha[config_ztha_var_json]:
                        for dict_ztha_type in data_ztha[config_ztha_var_json][ident]:
                            self.ztha_type[dict_ztha_type["key"]] = ident

                else:
                    QMessageBox.information(None, information_jsonfile_error, table_name)

        if self.season[0] == selected_season_button0_label:
            table_name = config_land_cover_file_summer_json
        elif self.season[0] == selected_season_button1_label:
            table_name = config_land_cover_file_winter_json
        # UH ordre : occupation du sol/ thématique/ abattement-production/ pratiques culturales,
        # drainage, pente
        # items obligatoires : occupation du sol/ thématique/ abattement-production
        # pas d'items pratiques culturales dans abattement
        # UH; #TODO: ajouter gestion drainage
        with open(self.path + table_name) as jsfile:
            data_land_cover = json.load(jsfile)
            if config_UH_var_json in data_land_cover:
                for land_cover_dict in data_land_cover[config_UH_var_json]:
                    self.land_cover[land_cover_dict] = int(data_land_cover[config_UH_var_json][land_cover_dict][config_UH_value_var_json])
                    if data_land_cover[config_UH_var_json][land_cover_dict][config_UH_abatement_var_json] == str(True):
                        # pas de practices pour abatement
                        self.abatement_type.append(int(data_land_cover[config_UH_var_json][land_cover_dict][config_UH_value_var_json]))

                        dict_thematique_abatement = {studied_element_button0_label: self.abatement_water, studied_element_button2_label: self.abatement_phyto,
                                                      studied_element_button1_label: self.abatement_mes}
                        for thematique in dict_thematique_abatement:
                            for test_key in data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_abatement_var_json]:
                                list_key = []
                                # test if drain keys :
                                if not test_key == config_UH_drain_0_var_json and not test_key == config_UH_drain_1_var_json and not test_key == config_UH_drain_2_var_json and not test_key == config_UH_drain_3_var_json:

                                    # pas de drainage, on teste la pente
                                    # test if slope keys :
                                    if not test_key == config_UH_low_slope_var_json and not test_key == config_UH_medium_slope_var_json and not test_key == config_UH_high_slope_var_json:
                                        # pas de drainage et pas de pente. Juste une seule valeur d'abattement
                                        # on copie 12 fois la valeur (4 type de drainage x 3 type de pentes)
                                        for i in range(12):
                                            list_key.append(
                                                float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                          config_UH_abatement_var_json]))
                                    else : # pas de drainage mais présence de trois pentes
                                        # on copie 4 fois la valeur (4 type de drainage)
                                        for i in range(4):
                                            for key in data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                config_UH_abatement_var_json]:
                                                list_key.append(
                                                    float(
                                                        data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                            config_UH_abatement_var_json][key]))
                                else : # présence de drainage
                                    for key in data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                        config_UH_abatement_var_json]:
                                        #pour chaque valeur de drainage, il est possible ou non d'avoir les trois classes de pentes
                                        for key_slope in data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                        config_UH_abatement_var_json][config_UH_drain_0_var_json]: # première valeur de drainage
                                            if not key_slope == config_UH_low_slope_var_json and not test_key == config_UH_medium_slope_var_json and not test_key == config_UH_high_slope_var_json:
                                            # pas de pente; on copie trois fois la valeur
                                                for i in range(3):
                                                    list_key.append(
                                                        float(data_land_cover[config_UH_var_json][land_cover_dict][
                                                                  thematique][
                                                                  config_UH_abatement_var_json][config_UH_drain_0_var_json]))
                                            else : # présence des trois classes de pentes
                                                for key in \
                                                data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                    config_UH_abatement_var_json][config_UH_drain_0_var_json]:
                                                    list_key.append(
                                                        float(
                                                            data_land_cover[config_UH_var_json][land_cover_dict][
                                                                thematique][
                                                                config_UH_abatement_var_json][config_UH_drain_0_var_json][key]))
                                        for key_slope in data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                        config_UH_abatement_var_json][config_UH_drain_1_var_json]: # deuxième valeur de drainage
                                            if not key_slope == config_UH_low_slope_var_json and not test_key == config_UH_medium_slope_var_json and not test_key == config_UH_high_slope_var_json:
                                            # pas de pente; on copie trois fois la valeur
                                                for i in range(3):
                                                    list_key.append(
                                                        float(data_land_cover[config_UH_var_json][land_cover_dict][
                                                                  thematique][
                                                                  config_UH_abatement_var_json][config_UH_drain_1_var_json]))
                                            else : # présence des trois classes de pentes
                                                for key in \
                                                data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                    config_UH_abatement_var_json][config_UH_drain_1_var_json]:
                                                    list_key.append(
                                                        float(
                                                            data_land_cover[config_UH_var_json][land_cover_dict][
                                                                thematique][
                                                                config_UH_abatement_var_json][config_UH_drain_1_var_json][key]))
                                        for key_slope in data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                        config_UH_abatement_var_json][config_UH_drain_2_var_json]: # troisième valeur de drainage
                                            if not key_slope == config_UH_low_slope_var_json and not test_key == config_UH_medium_slope_var_json and not test_key == config_UH_high_slope_var_json:
                                            # pas de pente; on copie trois fois la valeur
                                                for i in range(3):
                                                    list_key.append(
                                                        float(data_land_cover[config_UH_var_json][land_cover_dict][
                                                                  thematique][
                                                                  config_UH_abatement_var_json][config_UH_drain_2_var_json]))
                                            else : # présence des trois classes de pentes
                                                for key in \
                                                data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                    config_UH_abatement_var_json][config_UH_drain_2_var_json]:
                                                    list_key.append(
                                                        float(
                                                            data_land_cover[config_UH_var_json][land_cover_dict][
                                                                thematique][
                                                                config_UH_abatement_var_json][config_UH_drain_2_var_json][key]))

                                        for key_slope in data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                        config_UH_abatement_var_json][config_UH_drain_3_var_json]: # quatrième valeur de drainage
                                            if not key_slope == config_UH_low_slope_var_json and not test_key == config_UH_medium_slope_var_json and not test_key == config_UH_high_slope_var_json:
                                            # pas de pente; on copie trois fois la valeur
                                                for i in range(3):
                                                    list_key.append(
                                                        float(data_land_cover[config_UH_var_json][land_cover_dict][
                                                                  thematique][
                                                                  config_UH_abatement_var_json][config_UH_drain_3_var_json]))
                                            else : # présence des trois classes de pentes
                                                for key in \
                                                data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                    config_UH_abatement_var_json][config_UH_drain_3_var_json]:
                                                    list_key.append(
                                                        float(
                                                            data_land_cover[config_UH_var_json][land_cover_dict][
                                                                thematique][
                                                                config_UH_abatement_var_json][config_UH_drain_3_var_json][key]))


                            dict_thematique_abatement[thematique][
                                int(data_land_cover[config_UH_var_json][land_cover_dict][config_UH_value_var_json])] = list_key
                            
                        self.abatement = copy.deepcopy(self.abatement_phyto)

                    if data_land_cover[config_UH_var_json][land_cover_dict][config_UH_production_var_json] == str(True):
                        self.production_type.append(int(data_land_cover[config_UH_var_json][land_cover_dict][config_UH_value_var_json]))
                        # practice type, drainage  and slope type are optional, we need to test if absence :

                        # find if practices key exist; if False, get slope key instead
                        practices_key_bool = True
                        slope_key_bool = True

                        dict_thematique_production={studied_element_button0_label : self.production_water,studied_element_button2_label : self.production_phyto,
                                                    studied_element_button1_label :self.production_mes}
                        for thematique in dict_thematique_production:
                            for test_key in data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json]:
                                if not test_key.startswith('practice'):
                                    practices_key_bool = False
                                    # test if slope keys :
                                    if not test_key == config_UH_low_slope_var_json and not test_key == config_UH_medium_slope_var_json and not test_key == config_UH_high_slope_var_json:
                                        slope_key_bool = False

                            n = 0
                            practices_values = {}
                            while n < len(self.practices):
                                n = n + 1
                                list_key = []
                                if not practices_key_bool:  # une seule pratique
                                    if slope_key_bool:  # une seule pratique et plusieurs classes de pentes
                                        for key in data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json]:
                                            list_key.append(
                                                float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json][key]))
                                    else:  # une seule pratique et une seule classe de pente
                                        list_key.append(float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json]))
                                        list_key.append(float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][
                                                                  config_UH_production_var_json]))  # on copie trois fois pour "mimer" les 3 classes de pente
                                        list_key.append(float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json]))
                                else:  # plusieurs pratiques
                                    if slope_key_bool:  # plusieurs pratiques et plusieurs classes de pente
                                        nb_practice = "practice" + str(n)
                                        for key in data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json][nb_practice]:
                                            list_key.append(float(
                                                data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json][nb_practice][
                                                    key]))
                                    else:  # plusieurs pratiques et une seule classe de pente
                                        nb_practice = "practice" + str(n)
                                        list_key.append(
                                            float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json][nb_practice]))
                                        list_key.append(float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json][
                                                                  nb_practice]))  # on copie trois fois pour "mimer" les 3 classes de pente
                                        list_key.append(
                                            float(data_land_cover[config_UH_var_json][land_cover_dict][thematique][config_UH_production_var_json][nb_practice]))

                                practices_values[n] = list_key

                            dict_thematique_production[thematique][int(data_land_cover[config_UH_var_json][land_cover_dict][config_UH_value_var_json])] = practices_values
                            practices_key_bool = True
                            slope_key_bool = True
                        self.production=copy.deepcopy(self.production_phyto)

        # TE
        if self.season[0] == selected_season_button0_label:
            table_name = config_line_type_file_summer_json
        elif self.season[0] == selected_season_button1_label:
            table_name = config_line_type_file_winter_json

        with open(self.path + table_name) as jsfile:
            data_line_type = json.load(jsfile)
            if "TE" in data_line_type:
                for line_type_dict in data_line_type["TE"]:
                    self.line_type[line_type_dict] = int(data_line_type["TE"][line_type_dict]["value"])
                    if data_line_type["TE"][line_type_dict]["abatement_long"] == str(True):
                        dict_abatement_long = {studied_element_button0_label: self.abatement_long_water, studied_element_button2_label: self.abatement_long_phyto,
                                                      studied_element_button1_label: self.abatement_long_mes}
                        self.abatement_type_long.append(int(data_line_type["TE"][line_type_dict]["value"]))
                        for thematique in dict_abatement_long:
                            dict_abatement_long[thematique]=float(data_line_type["TE"][line_type_dict][thematique]["abatement_long"])
                        self.abatement_long=copy.deepcopy(self.abatement_long_phyto)


                    if data_line_type["TE"][line_type_dict]["abatement_lat"] == str(True):
                        dict_abatement_lat = {studied_element_button0_label: self.abatement_lat_water, studied_element_button2_label: self.abatement_lat_phyto,
                                               studied_element_button1_label: self.abatement_lat_mes}
                        self.abatement_type_lat.append(int(data_line_type["TE"][line_type_dict]["value"]))
                        for thematique in dict_abatement_lat:
                            dict_abatement_lat[thematique] = float(data_line_type["TE"][line_type_dict][thematique]["abatement_lat"])
                        self.abatement_lat = copy.deepcopy(self.abatement_lat_phyto)








