# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeomelbaSpirit
                                 A QGIS plugin
 Based on GeoMelba software, meant to be used with the serious game CAUSERIE.
 This file contains the functions to use when the user configure the dock widget.
 Buttons and widget of the dock widget are controlled with functions from this file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-24
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Jules Grillot / INRAE
        email                : jules.grillot@inrae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""

import json
import copy
import os
# Import personnal modules
from ..dictionnaire import data_folder, watershed_prefix, config_practices_file_json, config_slope_file_json, \
    config_land_cover_file_json, config_line_type_file_json, config_ztha_file_json, \
    config_land_cover_file_winter_json, config_line_type_file_winter_json, config_ztha_file_winter_json, \
    config_land_cover_file_summer_json, config_line_type_file_summer_json, config_ztha_file_summer_json, \
    information_jsonfile_error


class ConfigFilesImportJS:

    def __init__(self, path=None, watershed_name=None, season=None):
        # Get multiple parameters from the CSV in the watershed directory.
        self.practices = {}
        self.slope = {}
        self.land_cover = {}
        self.abatement_type = []
        self.abatement = {}
        self.abatement_water = {}
        self.abatement_mes = {}
        self.abatement_phyto = {}
        self.production_type = []
        self.production = {}
        self.production_water = {}
        self.production_mes = {}
        self.production_phyto = {}
        self.line_type = {}
        self.abatement_type_long = []
        self.abatement_type_lat = []
        self.abatement_long = {}
        self.abatement_long_water = {}
        self.abatement_long_mes = {}
        self.abatement_long_phyto = {}
        self.abatement_lat = {}
        self.abatement_lat_water = {}
        self.abatement_lat_mes = {}
        self.abatement_lat_phyto = {}
        self.ztha_type = {}
        self.path = path + data_folder + watershed_prefix + watershed_name + "/"
        self.season = season

        self.import_config_files()

    def import_config_files(self):
        table_name = config_practices_file_json

        with open(self.path + table_name) as jsfile:
            data_agricultural_practices = json.load(jsfile)
            if "agricultural_practices" in data_agricultural_practices:
                for key in data_agricultural_practices["agricultural_practices"]:
                    self.practices[key] = int(data_agricultural_practices["agricultural_practices"][key])
            else:
                QMessageBox.information(None, information_jsonfile_error, table_name)

        table_name = config_slope_file_json
        with open(self.path + table_name) as jsfile:
            data_slope = json.load(jsfile)
            if "slope" in data_slope:
                for key in data_slope["slope"]:
                    self.slope[key] = int(data_slope["slope"][key]["slope_min"]), \
                        int(data_slope["slope"][key]["slope_max"])
            else:
                QMessageBox.information(None, information_jsonfile_error, table_name)

        if self.season[0] == 'Eté':
            table_name = config_ztha_file_summer_json
        elif self.season[0] == 'Hiver':
            table_name = config_ztha_file_winter_json

        if os.path.exists(self.path + table_name):
            with open(self.path + table_name) as jsfile:
                data_ztha = json.load(jsfile)
                if "ztha" in data_ztha:
                    for ident in data_ztha["ztha"]:
                        for dict_ztha_type in data_ztha["ztha"][ident]:
                            self.ztha_type[dict_ztha_type["key"]] = ident

                else:
                    QMessageBox.information(None, information_jsonfile_error, table_name)

        if self.season[0] == 'Eté':
            table_name = config_land_cover_file_summer_json
        elif self.season[0] == 'Hiver':
            table_name = config_land_cover_file_winter_json

        # UH; #TODO: ajouter gestion drainage
        with open(self.path + table_name) as jsfile:
            data_land_cover = json.load(jsfile)
            if "UH" in data_land_cover:
                for land_cover_dict in data_land_cover["UH"]:
                    self.land_cover[land_cover_dict] = int(data_land_cover["UH"][land_cover_dict]["value"])
                    if data_land_cover["UH"][land_cover_dict]["abatement"] == str(True):
                        # pas de practices pour abatement
                        self.abatement_type.append(int(data_land_cover["UH"][land_cover_dict]["value"]))
                        slope_key_bool = True
                        dict_thematique_abatement = {"eau": self.abatement_water, "PPP": self.abatement_phyto,
                                                      "mes": self.abatement_mes}
                        for thematique in dict_thematique_abatement:
                            for test_key in data_land_cover["UH"][land_cover_dict][thematique]["abatement"]:
                                # test if slope keys :
                                if not test_key == "low_slope" and not test_key == "medium_slope" and not test_key == "high_slope":
                                    slope_key_bool = False
                                list_key = []
                                if slope_key_bool:  # plusieurs classes de pentes
                                    for key in data_land_cover["UH"][land_cover_dict][thematique]["abatement"]:
                                        list_key.append(
                                            float(
                                                data_land_cover["UH"][land_cover_dict][thematique]["abatement"][key]))
                                else:  # une seule classe de pente
                                    list_key.append(
                                        float(data_land_cover["UH"][land_cover_dict][thematique]["abatement"]))
                                    list_key.append(float(data_land_cover["UH"][land_cover_dict][thematique][
                                                              "abatement"]))  # on copie trois fois pour "mimer" les 3 classes de pente
                                    list_key.append(
                                        float(data_land_cover["UH"][land_cover_dict][thematique]["abatement"]))

                            dict_thematique_abatement[thematique][
                                int(data_land_cover["UH"][land_cover_dict]["value"])] = list_key
                            slope_key_bool = True
                        self.abatement = copy.deepcopy(self.abatement_phyto)

                    if data_land_cover["UH"][land_cover_dict]["production"] == str(True):
                        self.production_type.append(int(data_land_cover["UH"][land_cover_dict]["value"]))
                        # practice type and slope type are optional, we need to test if absence :
                        # attention à l'ordre : practices en premier (x items), slope en second (3 items)
                        # find if practices key exist; if False, get slope key instead
                        practices_key_bool = True
                        slope_key_bool = True

                        dict_thematique_production={"eau" : self.production_water,"PPP" : self.production_phyto,
                                                    "mes":self.production_mes}
                        for thematique in dict_thematique_production:
                            for test_key in data_land_cover["UH"][land_cover_dict][thematique]["production"]:
                                if not test_key.startswith('practice'):
                                    practices_key_bool = False
                                    # test if slope keys :
                                    if not test_key == "low_slope" and not test_key == "medium_slope" and not test_key == "high_slope":
                                        slope_key_bool = False

                            n = 0
                            practices_values = {}
                            while n < len(self.practices):
                                n = n + 1
                                list_key = []
                                if not practices_key_bool:  # une seule pratique
                                    if slope_key_bool:  # une seule pratique et plusieurs classes de pentes
                                        for key in data_land_cover["UH"][land_cover_dict][thematique]["production"]:
                                            list_key.append(
                                                float(data_land_cover["UH"][land_cover_dict][thematique]["production"][key]))
                                    else:  # une seule pratique et une seule classe de pente
                                        list_key.append(float(data_land_cover["UH"][land_cover_dict][thematique]["production"]))
                                        list_key.append(float(data_land_cover["UH"][land_cover_dict][thematique][
                                                                  "production"]))  # on copie trois fois pour "mimer" les 3 classes de pente
                                        list_key.append(float(data_land_cover["UH"][land_cover_dict][thematique]["production"]))
                                else:  # plusieurs pratiques
                                    if slope_key_bool:  # plusieurs pratiques et plusieurs classes de pente
                                        nb_practice = "practice" + str(n)
                                        for key in data_land_cover["UH"][land_cover_dict][thematique]["production"][nb_practice]:
                                            list_key.append(float(
                                                data_land_cover["UH"][land_cover_dict][thematique]["production"][nb_practice][
                                                    key]))
                                    else:  # plusieurs pratiques et une seule classe de pente
                                        nb_practice = "practice" + str(n)
                                        list_key.append(
                                            float(data_land_cover["UH"][land_cover_dict][thematique]["production"][nb_practice]))
                                        list_key.append(float(data_land_cover["UH"][land_cover_dict][thematique]["production"][
                                                                  nb_practice]))  # on copie trois fois pour "mimer" les 3 classes de pente
                                        list_key.append(
                                            float(data_land_cover["UH"][land_cover_dict][thematique]["production"][nb_practice]))

                                practices_values[n] = list_key

                            dict_thematique_production[thematique][int(data_land_cover["UH"][land_cover_dict]["value"])] = practices_values
                            practices_key_bool = True
                            slope_key_bool = True
                        self.production=copy.deepcopy(self.production_phyto)

        # TE







