# -*- coding: utf-8 -*-
"""
/***************************************************************************
 GeomelbaSpirit
                                 A QGIS plugin
 Based on GeoMelba software, meant to be used with the serious game CAUSERIE.
 This file contains the functions to use when the user configure the dock widget.
 Buttons and widget of the dock widget are controlled with functions from this file.
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                              -------------------
        begin                : 2021-08-24
        git sha              : $Format:%H$
        copyright            : (C) 2021 by Jules Grillot / INRAE
        email                : jules.grillot@inrae.fr
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
"""
from .tab_management import TabManagement
from .interface_tools.interface_management import UiCreationOwnerModification
from ...dictionnaire import owner_tab_name


class CoverCreationTab (TabManagement):

    def __init__(self, parent=None, project=None, parcel_layer=None, max_owner=None):
        """Concern the tab creation of the owner cover creation :
        - multiple buttons depending on the number of owner
        - spinboxes to switch parcels between two owner
        """
        super(CoverCreationTab, self).__init__(tab_widget=parent.tab_widget)
        self.tab_widget.setTabText(self.tab_index_owner, owner_tab_name)
        # If there is no owner, the tab is disabled because it's useless to create cover or switch ownership.
        if max_owner == 0:
            self.tab_widget.setTabEnabled(self.tab_index_owner, False)
        else:
            # Button and spinboxes creation
            self.ui_creation = UiCreationOwnerModification(parent, parcel_layer, project)
            self.ui_creation.init_owner(self.tab_widget, self.tab_index_owner, max_owner)
        # self.text_owner.setSource(QUrl.fromLocalFile(infos_tab_owner_edit))
